import type {
  ConceptEdge,
  ConceptNode,
  ConceptStatus,
} from "@/lib/types";

export const DOMAIN_COLORS: Record<string, string> = {
  Mathematics: "#f5a66d",
  Physics: "#77c7e8",
  Chemistry: "#b29af4",
  "Computer Science": "#78d7b5",
  Statistics: "#ef8eb9",
  General: "#d5d8e6",
};

export const STATUS_COLORS: Record<ConceptStatus, string> = {
  learning: "#f5a66d",
  mastered: "#78d7b5",
  suggested: "#9eb9dc",
  locked: "#697080",
};

export const DOMAIN_CENTERS: Record<string, [number, number, number]> = {
  Mathematics: [-3.1, 0.2, 0],
  Physics: [6.8, 2.7, -2.4],
  Chemistry: [7.3, -4.5, 1.8],
  "Computer Science": [-1.4, 7.4, -5.2],
  Statistics: [-7.3, 5.2, 2.5],
  General: [0, 0, 0],
};

export const STARTER_NODES: ConceptNode[] = [
  {
    id: "arithmetic",
    label: "Arithmetic",
    domain: "Mathematics",
    description: "Number operations and their relationships.",
    status: "mastered",
    mastery: 94,
    position: [-7.2, -1.2, 0.2],
  },
  {
    id: "fractions",
    label: "Fractions",
    domain: "Mathematics",
    description: "Parts, ratios, and equivalent representations.",
    status: "mastered",
    mastery: 86,
    position: [-6.2, 1.4, 0.9],
  },
  {
    id: "ratios",
    label: "Ratios",
    domain: "Mathematics",
    description: "Comparing quantities multiplicatively.",
    status: "mastered",
    mastery: 82,
    position: [-5.2, -0.3, -1.1],
  },
  {
    id: "expressions",
    label: "Expressions",
    domain: "Mathematics",
    description: "Combining symbols, values, and operations.",
    status: "mastered",
    mastery: 78,
    position: [-3.9, -1.7, 0.8],
  },
  {
    id: "linear-equations",
    label: "Linear equations",
    domain: "Mathematics",
    description: "Equality, unknowns, and reversible operations.",
    status: "mastered",
    mastery: 76,
    position: [-3.3, 0.3, -0.2],
  },
  {
    id: "factoring",
    label: "Factoring",
    domain: "Mathematics",
    description: "Rewriting expressions to reveal their multiplicative structure.",
    status: "learning",
    mastery: 48,
    position: [-1.1, -1, 0.7],
  },
  {
    id: "functions",
    label: "Functions",
    domain: "Mathematics",
    description: "Rules that map inputs to outputs.",
    status: "suggested",
    mastery: 18,
    position: [0.5, 0.6, -0.5],
  },
  {
    id: "limits",
    label: "Limits",
    domain: "Mathematics",
    description: "What a function approaches near a point.",
    status: "suggested",
    mastery: 12,
    position: [2.3, 1.8, 0.7],
  },
  {
    id: "derivatives",
    label: "Derivatives",
    domain: "Mathematics",
    description: "Instantaneous change and local linear behavior.",
    status: "locked",
    mastery: 0,
    position: [3.8, 0, -1.1],
  },
  {
    id: "integrals",
    label: "Integrals",
    domain: "Mathematics",
    description: "Accumulation, area, and inverse rates of change.",
    status: "locked",
    mastery: 0,
    position: [4.5, -2.1, 0.7],
  },
  {
    id: "units",
    label: "Units",
    domain: "Physics",
    description: "Dimensional meaning and consistent measurement.",
    status: "suggested",
    mastery: 24,
    position: [4.5, 3.1, -2.5],
  },
  {
    id: "vectors",
    label: "Vectors",
    domain: "Physics",
    description: "Quantities with magnitude and direction.",
    status: "locked",
    mastery: 0,
    position: [6.4, 4.7, -3.5],
  },
  {
    id: "kinematics",
    label: "Kinematics",
    domain: "Physics",
    description: "Describing motion through position, velocity, and acceleration.",
    status: "locked",
    mastery: 0,
    position: [7.7, 2.5, -1.7],
  },
  {
    id: "forces",
    label: "Forces",
    domain: "Physics",
    description: "Interactions that change motion.",
    status: "locked",
    mastery: 0,
    position: [8.8, 4.3, -2.9],
  },
  {
    id: "energy",
    label: "Energy",
    domain: "Physics",
    description: "A conserved accounting system for physical change.",
    status: "locked",
    mastery: 0,
    position: [9, 1.2, -3.7],
  },
  {
    id: "atoms",
    label: "Atomic structure",
    domain: "Chemistry",
    description: "Particles, charge, and electron organization.",
    status: "suggested",
    mastery: 8,
    position: [5.2, -4.2, 2.2],
  },
  {
    id: "moles",
    label: "Moles",
    domain: "Chemistry",
    description: "Counting particles through measurable amounts.",
    status: "locked",
    mastery: 0,
    position: [6.4, -6.1, 1],
  },
  {
    id: "bonding",
    label: "Bonding",
    domain: "Chemistry",
    description: "Why atoms form stable structures.",
    status: "locked",
    mastery: 0,
    position: [7.7, -3.2, 3.5],
  },
  {
    id: "stoichiometry",
    label: "Stoichiometry",
    domain: "Chemistry",
    description: "Quantitative relationships in chemical reactions.",
    status: "locked",
    mastery: 0,
    position: [8.7, -5.6, 2],
  },
  {
    id: "chemical-energy",
    label: "Thermochemistry",
    domain: "Chemistry",
    description: "Energy transferred during chemical change.",
    status: "locked",
    mastery: 0,
    position: [9.6, -3.7, 0.8],
  },
  {
    id: "logic",
    label: "Logic",
    domain: "Computer Science",
    description: "Truth, implication, and valid inference.",
    status: "suggested",
    mastery: 14,
    position: [-3.8, 6.3, -4.4],
  },
  {
    id: "variables",
    label: "Variables",
    domain: "Computer Science",
    description: "Names for values and changing state.",
    status: "suggested",
    mastery: 10,
    position: [-1.8, 8.2, -6.1],
  },
  {
    id: "control-flow",
    label: "Control flow",
    domain: "Computer Science",
    description: "Conditions, repetition, and execution paths.",
    status: "locked",
    mastery: 0,
    position: [0.1, 6.4, -5.3],
  },
  {
    id: "algorithms",
    label: "Algorithms",
    domain: "Computer Science",
    description: "Precise procedures for solving classes of problems.",
    status: "locked",
    mastery: 0,
    position: [-0.3, 9.4, -4.2],
  },
  {
    id: "data-structures",
    label: "Data structures",
    domain: "Computer Science",
    description: "Ways to organize information around operations.",
    status: "locked",
    mastery: 0,
    position: [1.2, 8.2, -6.8],
  },
  {
    id: "probability",
    label: "Probability",
    domain: "Statistics",
    description: "Reasoning about uncertain outcomes.",
    status: "suggested",
    mastery: 16,
    position: [-6.1, 3.3, 2.2],
  },
  {
    id: "distributions",
    label: "Distributions",
    domain: "Statistics",
    description: "Patterns describing how outcomes vary.",
    status: "locked",
    mastery: 0,
    position: [-8, 5.4, 3.5],
  },
  {
    id: "inference",
    label: "Inference",
    domain: "Statistics",
    description: "Learning about populations from samples.",
    status: "locked",
    mastery: 0,
    position: [-7, 7, 1.5],
  },
];

export const STARTER_EDGES: ConceptEdge[] = [
  { from: "arithmetic", to: "fractions", relation: "builds-to" },
  { from: "arithmetic", to: "expressions", relation: "builds-to" },
  { from: "fractions", to: "ratios", relation: "builds-to" },
  { from: "ratios", to: "linear-equations", relation: "builds-to" },
  { from: "expressions", to: "linear-equations", relation: "builds-to" },
  { from: "expressions", to: "factoring", relation: "builds-to" },
  { from: "linear-equations", to: "functions", relation: "builds-to" },
  { from: "factoring", to: "functions", relation: "builds-to" },
  { from: "functions", to: "limits", relation: "builds-to" },
  { from: "limits", to: "derivatives", relation: "builds-to" },
  { from: "derivatives", to: "integrals", relation: "builds-to" },
  { from: "ratios", to: "units", relation: "applies-in" },
  { from: "functions", to: "kinematics", relation: "applies-in" },
  { from: "derivatives", to: "kinematics", relation: "applies-in" },
  { from: "units", to: "vectors", relation: "builds-to" },
  { from: "vectors", to: "kinematics", relation: "builds-to" },
  { from: "kinematics", to: "forces", relation: "builds-to" },
  { from: "forces", to: "energy", relation: "builds-to" },
  { from: "ratios", to: "moles", relation: "applies-in" },
  { from: "atoms", to: "bonding", relation: "builds-to" },
  { from: "moles", to: "stoichiometry", relation: "builds-to" },
  { from: "bonding", to: "stoichiometry", relation: "builds-to" },
  { from: "energy", to: "chemical-energy", relation: "adjacent" },
  { from: "stoichiometry", to: "chemical-energy", relation: "builds-to" },
  { from: "logic", to: "control-flow", relation: "builds-to" },
  { from: "variables", to: "control-flow", relation: "builds-to" },
  { from: "control-flow", to: "algorithms", relation: "builds-to" },
  { from: "algorithms", to: "data-structures", relation: "builds-to" },
  { from: "functions", to: "variables", relation: "adjacent" },
  { from: "ratios", to: "probability", relation: "applies-in" },
  { from: "probability", to: "distributions", relation: "builds-to" },
  { from: "distributions", to: "inference", relation: "builds-to" },
];

function hashString(value: string) {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return Math.abs(hash);
}

export function positionForConcept(
  id: string,
  domain: string,
): [number, number, number] {
  const center = DOMAIN_CENTERS[domain] ?? DOMAIN_CENTERS.General;
  const hash = hashString(`${domain}:${id}`);
  const angle = ((hash % 360) * Math.PI) / 180;
  const elevation = ((((hash >> 4) % 160) - 80) / 80) * 1.8;
  const radius = 2.1 + ((hash >> 8) % 180) / 100;

  return [
    center[0] + Math.cos(angle) * radius,
    center[1] + elevation,
    center[2] + Math.sin(angle) * radius,
  ];
}
