import type {
  ConceptEdge,
  ConceptNode,
  ConceptStatus,
} from "@/lib/types";

export const STATUS_COLORS: Record<ConceptStatus, string> = {
  learning: "#f5a66d",
  mastered: "#78d7b5",
  suggested: "#9eb9dc",
  locked: "#697080",
};

export function statusLabel(status: ConceptStatus) {
  if (status === "learning") return "In focus";
  if (status === "mastered") return "Mastered";
  if (status === "suggested") return "Within reach";
  return "Further out";
}

export const STARTER_NODES: ConceptNode[] = [
  {
    id: "arithmetic",
    label: "Arithmetic",
    domain: "Mathematics",
    description: "Number operations and their relationships.",
    status: "mastered",
    mastery: 94,
  },
  {
    id: "fractions",
    label: "Fractions",
    domain: "Mathematics",
    description: "Parts, ratios, and equivalent representations.",
    status: "mastered",
    mastery: 86,
  },
  {
    id: "equivalent-fractions",
    label: "Equivalent fractions",
    domain: "Mathematics",
    description: "Different numerators and denominators naming the same amount.",
    status: "mastered",
    mastery: 90,
  },
  {
    id: "ratios",
    label: "Ratios",
    domain: "Mathematics",
    description: "Comparing quantities multiplicatively.",
    status: "mastered",
    mastery: 82,
  },
  {
    id: "expressions",
    label: "Expressions",
    domain: "Mathematics",
    description: "Combining symbols, values, and operations.",
    status: "mastered",
    mastery: 78,
  },
  {
    id: "linear-equations",
    label: "Linear equations",
    domain: "Mathematics",
    description: "Equality, unknowns, and reversible operations.",
    status: "mastered",
    mastery: 76,
  },
  {
    id: "factoring",
    label: "Factoring",
    domain: "Mathematics",
    description: "Rewriting expressions to reveal their multiplicative structure.",
    status: "learning",
    mastery: 48,
  },
  {
    id: "common-factors",
    label: "Greatest common factor",
    domain: "Mathematics",
    description: "Pulling the largest shared factor out of every term.",
    status: "mastered",
    mastery: 81,
  },
  {
    id: "difference-of-squares",
    label: "Difference of squares",
    domain: "Mathematics",
    description: "Rewriting a² − b² as (a − b)(a + b).",
    status: "suggested",
    mastery: 34,
  },
  {
    id: "functions",
    label: "Functions",
    domain: "Mathematics",
    description: "Rules that map inputs to outputs.",
    status: "suggested",
    mastery: 18,
  },
  {
    id: "limits",
    label: "Limits",
    domain: "Mathematics",
    description: "What a function approaches near a point.",
    status: "suggested",
    mastery: 12,
  },
  {
    id: "continuity",
    label: "Continuity",
    domain: "Mathematics",
    description: "A function with no break, jump, or hole at a point.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "derivatives",
    label: "Derivatives",
    domain: "Mathematics",
    description: "Instantaneous change and local linear behavior.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "chain-rule",
    label: "Chain rule",
    domain: "Mathematics",
    description: "Differentiating a function nested inside another.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "integrals",
    label: "Integrals",
    domain: "Mathematics",
    description: "Accumulation, area, and inverse rates of change.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "units",
    label: "Units",
    domain: "Physics",
    description: "Dimensional meaning and consistent measurement.",
    status: "suggested",
    mastery: 24,
  },
  {
    id: "vectors",
    label: "Vectors",
    domain: "Physics",
    description: "Quantities with magnitude and direction.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "kinematics",
    label: "Kinematics",
    domain: "Physics",
    description: "Describing motion through position, velocity, and acceleration.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "forces",
    label: "Forces",
    domain: "Physics",
    description: "Interactions that change motion.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "energy",
    label: "Energy",
    domain: "Physics",
    description: "A conserved accounting system for physical change.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "atoms",
    label: "Atomic structure",
    domain: "Chemistry",
    description: "Particles, charge, and electron organization.",
    status: "suggested",
    mastery: 8,
  },
  {
    id: "moles",
    label: "Moles",
    domain: "Chemistry",
    description: "Counting particles through measurable amounts.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "bonding",
    label: "Bonding",
    domain: "Chemistry",
    description: "Why atoms form stable structures.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "stoichiometry",
    label: "Stoichiometry",
    domain: "Chemistry",
    description: "Quantitative relationships in chemical reactions.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "chemical-energy",
    label: "Thermochemistry",
    domain: "Chemistry",
    description: "Energy transferred during chemical change.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "logic",
    label: "Logic",
    domain: "Computer Science",
    description: "Truth, implication, and valid inference.",
    status: "suggested",
    mastery: 14,
  },
  {
    id: "variables",
    label: "Variables",
    domain: "Computer Science",
    description: "Names for values and changing state.",
    status: "suggested",
    mastery: 10,
  },
  {
    id: "control-flow",
    label: "Control flow",
    domain: "Computer Science",
    description: "Conditions, repetition, and execution paths.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "algorithms",
    label: "Algorithms",
    domain: "Computer Science",
    description: "Precise procedures for solving classes of problems.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "data-structures",
    label: "Data structures",
    domain: "Computer Science",
    description: "Ways to organize information around operations.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "probability",
    label: "Probability",
    domain: "Statistics",
    description: "Reasoning about uncertain outcomes.",
    status: "suggested",
    mastery: 16,
  },
  {
    id: "distributions",
    label: "Distributions",
    domain: "Statistics",
    description: "Patterns describing how outcomes vary.",
    status: "locked",
    mastery: 0,
  },
  {
    id: "inference",
    label: "Inference",
    domain: "Statistics",
    description: "Learning about populations from samples.",
    status: "locked",
    mastery: 0,
  },
];

export const STARTER_EDGES: ConceptEdge[] = [
  { from: "arithmetic", to: "fractions", relation: "builds-to" },
  { from: "arithmetic", to: "expressions", relation: "builds-to" },
  { from: "fractions", to: "ratios", relation: "builds-to" },
  { from: "ratios", to: "linear-equations", relation: "builds-to" },
  { from: "expressions", to: "linear-equations", relation: "builds-to" },
  { from: "expressions", to: "factoring", relation: "builds-to" },
  { from: "linear-equations", to: "functions", relation: "builds-to" },
  { from: "factoring", to: "functions", relation: "builds-to" },
  { from: "functions", to: "limits", relation: "builds-to" },
  { from: "limits", to: "derivatives", relation: "builds-to" },
  { from: "derivatives", to: "integrals", relation: "builds-to" },
  { from: "fractions", to: "equivalent-fractions", relation: "builds-to" },
  { from: "factoring", to: "common-factors", relation: "builds-to" },
  { from: "factoring", to: "difference-of-squares", relation: "builds-to" },
  { from: "limits", to: "continuity", relation: "builds-to" },
  { from: "derivatives", to: "chain-rule", relation: "builds-to" },
  { from: "ratios", to: "units", relation: "applies-in" },
  { from: "functions", to: "kinematics", relation: "applies-in" },
  { from: "derivatives", to: "kinematics", relation: "applies-in" },
  { from: "units", to: "vectors", relation: "builds-to" },
  { from: "vectors", to: "kinematics", relation: "builds-to" },
  { from: "kinematics", to: "forces", relation: "builds-to" },
  { from: "forces", to: "energy", relation: "builds-to" },
  { from: "ratios", to: "moles", relation: "applies-in" },
  { from: "atoms", to: "bonding", relation: "builds-to" },
  { from: "moles", to: "stoichiometry", relation: "builds-to" },
  { from: "bonding", to: "stoichiometry", relation: "builds-to" },
  { from: "energy", to: "chemical-energy", relation: "adjacent" },
  { from: "stoichiometry", to: "chemical-energy", relation: "builds-to" },
  { from: "logic", to: "control-flow", relation: "builds-to" },
  { from: "variables", to: "control-flow", relation: "builds-to" },
  { from: "control-flow", to: "algorithms", relation: "builds-to" },
  { from: "algorithms", to: "data-structures", relation: "builds-to" },
  { from: "functions", to: "variables", relation: "adjacent" },
  { from: "ratios", to: "probability", relation: "applies-in" },
  { from: "probability", to: "distributions", relation: "builds-to" },
  { from: "distributions", to: "inference", relation: "builds-to" },
];
